
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backend
    username: backend
    password: backend
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

budgettracker:
  app:
    jwtSecret: b6953fcd86da7866706be8311074bc2591029d44f8f843efd9e39de575f04746
    jwtExpirationMs: 86400000